import React from 'react'
import Head from 'next/head'
import Footer from '../../components/Footer'


const Notification = () => {
  return (
    
    <div className='main-body body-f2f2f2'>
      <Head>
        <title>Thông báo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="robots" content="noindex" />
        <meta property="og:title" content="Thông báo" />
        <meta property="og:description" content="Conng ty Khatoco" />
        <meta property="og:site_name" content="Khatoco" />
      </Head>
      Thông báo
      <Footer />
    </div>
    
  )
}

export default Notification