// REDUX ACTION TYPES
export const TICK = 'TICK'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'
export const SETNOTIFICATION = 'SETNOTIFICATION'
export const UPDATE_LIST_USER = 'UPDATE_LIST_USER'
export const SHOW_XND = 'SHOW_XND'
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'
export const COUNT_MESSAGE = 'COUNT_MESSAGE'



