import React from "react";
import SideBarAdmin from "../components/sideBarAdmin/index"
import HeaderAdmin from "../components/headerAdmin/index"
import Head from 'next/head'

export default function Admin({ children}) {
  
  return (<>
    <Head>
      <title>Khatoco Admin</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="robots" content="noindex" />
      <meta property="og:title" content="Khatoco" />
      <meta property="og:description" content="Conng ty Khatoco" />
      <meta property="og:site_name" content="Khatoco" />
    </Head>
    <div className="main-admin flex">
      <div className="main-admin--left">
        <SideBarAdmin />
      </div>
      <div className="main-admin--right">
        <HeaderAdmin />
        <div className="main-admin--right__body">
          {children}
        </div>
      </div>
    </div>
  </>);
}
