import React from "react";

import Head from 'next/head'

export default function Admin({ children}) {
  
  return (<>
    <Head>
      <title>Khatoco Admin</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <meta property="og:site_name" content="Khatoco" />
    </Head>
    <div className="main-admin flex">
      <div className="main-admin--left">
      </div>
      <div className="main-admin--right">
        <div className="main-admin--right__body">
          {children}
        </div>
      </div>
    </div>
  </>);
}
