import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HeaderHome from '../components/home/Headerhome.js'
import Footer from '../components/footer'
import MainHome from '../components/home/mainHome.js'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Khatoco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="robots" content="noindex" />
      </Head>
      <div className='main-body body-f2f2f2'>
        <HeaderHome />
        <MainHome />
        <Footer />
      </div>

      
    </div>
  )
}
